### ISSUE TITLE
Cant make the thermostat work with an external thermometer

### ISSUE THREAD

**Issue by Fornball** [algirdasc/hass-floureon#19]
Do I have to use the thermostat as a switch or as a climate to use it with an external thermometer? Im kinda having issues with both. I'm supposed to use it like a generic termostat, right? So like here(from the official home assistant, generic thermostat page): 

```
# Example configuration.yaml entry
climate:
  - platform: generic_thermostat
    name: Study
    heater: switch.study_heater
    target_sensor: sensor.study_temperature
```

When in switch mode it doesnt adjust itself and I can only make it work by manually using switch.turn_on/off, (as far as I understand its supposed to set its temperature to 35 when on and to 5 when off?). Here is how it looks in the configuration.yaml file:
```
climate:
 - platform: generic_thermostat
   name: Thermostat_my_room
   heater: switch.my_room_thermostat_as_switch
   target_sensor: sensor.ble_temperature_thermometer


switch:
  platform: floureon
  name: my_room_thermostat_as_switch
  host: 192.168.138.99
  use_external_temp: true
```
When in climate mode it doesnt respond to any commands, turn on/off, set temperature, set hvac mode all dont work on the generic thermostat, but these do work on the orginal beok thermostat. Here is how it looks in the configuration.yaml file:
```
climate:
 - platform: floureon
   name: testing_thermostat
   host: 192.168.138.99
   use_external_temp: true
   
 - platform: generic_thermostat
   name: Thermostat_my_room
   heater: climate.testing_thermostat
   target_sensor: sensor.ble_temperature_thermometer
```
What am I doing wrong?
