### ISSUE TITLE
This entity ('climate.livingroom_floor') does not have a unique ID, therefore its settings cannot be managed from the UI.

### ISSUE THREAD

**Issue by prmfeddema** [algirdasc/hass-floureon#42]
Hi Everyone,

Quick questions - this might not be a bug/issue.

Upon installing this custom integration and managing the settings i get this error : "This entity ('climate.livingroom_floor') does not have a unique ID, therefore its settings cannot be managed from the UI." 

Is this normal behaviour  - if so i will create a unique id manually.. If not, any suggestions on how to handle this?

Thanks,

Pascal

**Comment by aritztg** [comment]
I solved it by just adding the `unique_id` entry in the yaml:
```yaml
climate:
  platform: floureon
  unique_id: beok_01
  name: Beok
  host: 192.168.0.43
  use_external_temp: false
```

Put something unique in your setup and you are good to go.
